import { SelectItem } from "../types/general";

export enum InputName {
  CitySelect = "citySelect",
}

export const CityOptions: SelectItem[] = [
  { label: "Cheyenne", value: "Cheyenne" },
  { label: "Madison", value: "Madison" },
  { label: "Charleston", value: "Charleston" },
  { label: "Olympia", value: "Olympia" },
  { label: "Richmond", value: "Richmond" },
  { label: "Montpelier", value: "Montpelier" },
  { label: "Salt Lake City", value: "Salt Lake City" },
  { label: "Austin", value: "Austin" },
  { label: "Nashville", value: "Nashville" },
  { label: "Pierre", value: "Pierre" },
  { label: "Columbia", value: "Columbia" },
  { label: "Providence", value: "Providence" },
  { label: "Harrisburg", value: "Harrisburg" },
  { label: "Salem", value: "Salem" },
  { label: "Oklahoma City", value: "Oklahoma City" },
  { label: "Columbus", value: "Columbus" },
  { label: "Bismarck", value: "Bismarck" },
  { label: "Rayleigh", value: "Rayleigh" },
  { label: "Albany", value: "Albany" },
  { label: "Santa Fe", value: "Santa Fe" },
  { label: "Trenton", value: "Trenton" },
  { label: "Concord", value: "Concord" },
  { label: "Carson City", value: "Carson City" },
  { label: "Lincoln", value: "Lincoln" },
  { label: "Helena", value: "Helena" },
  { label: "Jefferson City", value: "Jefferson City" },
  { label: "Jackson", value: "Jackson" },
  { label: "Saint Paul", value: "Saint Paul" },
  { label: "Lansing", value: "Lansing" },
  { label: "Boston", value: "Boston" },
  { label: "Annapolis", value: "Annapolis" },
  { label: "Augusta", value: "Augusta" },
  { label: "Baton Rouge", value: "Baton Rouge" },
  { label: "Frankfort", value: "Frankfort" },
  { label: "Topeka", value: "Topeka" },
  { label: "Des Moines", value: "Des Moines" },
  { label: "Indianapolis", value: "Indianapolis" },
  { label: "Springfield", value: "Springfield" },
  { label: "Boise", value: "Boise" },
  { label: "Honolulu", value: "Honolulu" },
  { label: "Atlanta", value: "Atlanta" },
  { label: "Tallahassee", value: "Tallahassee" },
  { label: "Dover", value: "Dover" },
  { label: "Hartford", value: "Hartford" },
  { label: "Denver", value: "Denver" },
  { label: "Sacramento", value: "Sacramento" },
  { label: "Little Rock", value: "Little Rock" },
  { label: "Phoenix", value: "Phoenix" },
  { label: "Juneau", value: "Juneau" },
  { label: "Montgomery", value: "Montgomery" },
];
